#!/usr/bin/env bash

main() {
  build
}

test() {
  webpack-dev-server
  echo "Open localhost:3003/test"
}

build() {
  NODE_ENV=production webpack
}

case "$1" in
  "" ) main ;;
  b | build ) build ;;
  t | test ) test ;;
esac
